service: passwordless
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  iam:
    role:
      statements:
        - Sid: DynamoDB
          Effect: Allow
          Action: 
          - dynamodb:PutItem
          - dynamodb:GetItem
          Resource: 
          - Fn::GetAtt:
            - OtpTable
            - Arn
        - Sid: SendEmail
          Effect: Allow
          Action:
          - ses:SendEmail
          - ses:SendRawEmail
          Resource: "*"

  environment:
    STAGE: ${self:custom.stage}

custom:
  stage: ${opt:stage, 'development'}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  sendotp:
    handler: bin/sendotp
    events:
      - http:
          path: /auth/send-otp
          method: post

plugins:
  - serverless-offline

resources:
  Resources:
    OtpTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Otp
        AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
        KeySchema:
        - AttributeName: Email
          KeyType: HASH
        TimeToLiveSpecification:
          Enabled: True
          AttributeName: ExpiresIn
        BillingMode: PAY_PER_REQUEST

#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
